[package]
name = "sts_card_maker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.5"
image = "0.24.5"
rayon = "1.6.1"
env_logger = "0.10.0"
log = "0.4.17"